namespace test.Scripts;

public class PerformancesListUtils
{
    // TODO ADD REVERSING METHODS FOR LISTS, TAKING A LIST AS PARAMETER AND RETURNING THE SAME LIST REVERSED
    
    // TODO ADD FILTERING UTIL TO REMOVE ALL NOT PRIME NUMBERS IN A LIST TAKEN AS PARAMETER,
    // MODIFIED BY REFERENCE, NO RETURNED VALUE

    // TODO ADD LIST RANDOMIZER, RETURNING A NEW LIST EQUIVALENT TO THE PARAMETER ONE CLONED AND RANDOMIZED
    
    
    // TODO SAME UTILS WITH ARRAYS AND COMPARE RESULTS
    
}